name: Continuous Integration
on: [push]
jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'
                dependencies:
                    - highest
                include:
                    - php: '7.4'
                      dependencies: lowest

        steps:
            - uses: actions/checkout@v1

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: --prefer-dist

            - name: CodeSniffer
              run: php vendor/bin/phpcs

            - name: PHPStan
              run: php vendor/bin/phpstan analyse

            - name: Psalm
              run: php vendor/bin/psalm

            - name: PHPUnit
              run: vendor/bin/phpunit

            - name: Upload coverage results to Coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  composer require --dev php-coveralls/php-coveralls phpunit/phpcov
                  php vendor/bin/phpcov merge --clover build/logs/clover.xml build/cov
                  php vendor/bin/php-coveralls -v
